### ISSUE TITLE
Uncaught module [tinymce.core.ui.Api] returned undefined

### ISSUE THREAD

**Issue by groundnation** [loyals-online/silverstripe-tinymce4#11]
Hi

Just updated (bump to tinyMCE 4.6.3) via composer and getting below error resulting in tinymce not showing;

theme.js:29
Uncaught module [tinymce.core.ui.Api] returned undefined

cheers
James

**Comment by gavro** [comment]
Yes, this is thing... You have to empty your silverstripe-cache folder. Things are getting cached via the tiny_mce_gzip php method and it appears it's not getting flushed via ?flush=1.

Could you try removing your silverstripe-cache manually and let me know if it does the trick?

**Comment by groundnation** [comment]
Yep, thats fixed it - many thanks (great module btw)

**Comment by ryan2johnson9** [comment]
I am using 4.7.4, used to be 4.5.2 and this change happened recently 

someone using our site reported this issue too but I do not get the issue. Does the user have to clear their browser cache? Is it just because of the update to tinyMCE?

Is there anything I can do as a developer except ask all our users to clear their browser cache?
